apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainwave-deployment
  labels:
    app: brainwave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainwave
  template:
    metadata:
      labels:
        app: brainwave
    spec:
      containers:
      - name: brainwave
        image: mohithp/brainwave
        ports:
        - containerPort: 80
